apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend-deployment
spec:
 selector:
   matchLabels:
    type: frontend
 replicas: 1
 template:
   metadata:
     labels:
       type: frontend
   spec:
    containers:
    - name: frontend
      image: rhkzl/frontend:6
      envFrom:
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m
